
spring:
  thymeleaf:
    cache: false

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://rm-bp181438h1s942d21oo.mysql.rds.aliyuncs.com:3306/seckill?useSSL=false&useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: zhaobin
    password: 15294834575zhaO
    hikari:
      pool-name: DateHikariCP
      minimum-idle: 5
      idle-timeout: 1800000
      maximum-pool-size: 10
      auto-commit: true
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1

  redis:
    #服务器地址
    host: 127.0.0.1
    port: 6379
    database: 0
    timeout: 10000ms
    lettuce:
      pool:
        max-active: 8
        max-wait: 10000ms
        max-idle: 8
        min-idle: 5

  rabbitmq:
    #服务器
    host: 127.0.0.1
    username: guest
    password: guest
    virtual-host: /
    port: 5672
    # 消费者数量
    listener:
      simple:
        concurrency: 10
        max-concurrency: 10
        # 每次从队列中取的消息个数，prefetch来限制Queue每次发送给每个消费者的消息数，设置为1表明，queue每次会发送1个消息给consumer，
        #等到收到consumer的ack后，queue才会继续发消息给consumer
        prefetch: 1
        # 消费者默认启动
        auto-startup: true
        #被拒绝重新进入队列
        default-requeue-rejected: true
    template:
      retry:
        enabled: true
        initial-interval: 1000ms
        max-attempts: 3
        max-interval: 10000ms
        multiplier: 1

mybatis-plus:
  mapper-locations: classpath*:/mapper/*Mapper.xml
  type-aliases-package: com.frank.seckill.pojo

logging:
  level:
    com.frank.seckill.mapper: debug